Refactor deployment workflow: Update AMI creation and tagging in prod.deploy.yml

diff --git a/.github/workflows/prod.deploy.yml b/.github/workflows/prod.deploy.yml
--- a/.github/workflows/prod.deploy.yml
+++ b/.github/workflows/prod.deploy.yml
@@ -160,14 +160,35 @@ jobs:
 
           echo "AMI is available. Creating new Launch Template version..."
           # Create a new version of the Launch Template with the updated AMI
-          aws ec2 create-launch-template-version --launch-template-id $TEMPLATE_ID --source-version 1 --launch-template-data '{"ImageId":"'"$AMI_ID"'"}'
-          # Get the latest version number
-          LATEST_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-id $TEMPLATE_ID --query 'LaunchTemplateVersions[-1].VersionNumber' --output text)
-          # Set the new version as the default
-          aws ec2 modify-launch-template --launch-template-id $TEMPLATE_ID --default-version $LATEST_VERSION
-          # Tag the new AMI
-          aws ec2 create-tags --resources $AMI_ID --tags Key=Name,Value=$AMI_NAME
-          echo "Launch Template updated with new AMI: $AMI_ID"
+            echo "Creating a new version of the Launch Template with updated AMI..."
+            aws ec2 create-launch-template-version \
+              --launch-template-id $TEMPLATE_ID \
+              --source-version 1 \
+              --launch-template-data '{"ImageId":"'"$AMI_ID"'", "TagSpecifications":[{"ResourceType":"instance","Tags":[{"Key":"Name","Value":"'"${{ github.event.inputs.version_Number }}"'"}]}]}' \
+              --version-description "${{ github.event.inputs.version_Number }}"
+
+            # Get the latest version number (sort by VersionNumber to ensure latest)
+            LATEST_VERSION=$(aws ec2 describe-launch-template-versions \
+              --launch-template-id $TEMPLATE_ID \
+              --query 'LaunchTemplateVersions | sort_by(@, &VersionNumber) | [-1].VersionNumber' \
+              --output text)
+
+            # Ensure we have the latest version number
+            if [ -z "$LATEST_VERSION" ]; then
+              echo "Error: Could not retrieve the latest version number."
+              exit 1
+            fi
+
+            echo "Latest version number is: $LATEST_VERSION"
+
+            # Set the new version as the default
+            echo "Setting the new version $LATEST_VERSION as the default..."
+            aws ec2 modify-launch-template \
+              --launch-template-id $TEMPLATE_ID \
+              --default-version $LATEST_VERSION
+
+            echo "Launch Template updated and default version set to $LATEST_VERSION."
+
 
 
       # Step 7: Trigger a Rolling Update in the Auto Scaling Group
